### ISSUE TITLE
Artwork shifted outside of croppable area on iPhone 6 and 6+

### ISSUE THREAD

**Issue by miwillhite** [sincerely/shiplib-ios-framework#19]
On devices 6 and 6+ the artwork gets shifted outside of the croppable area. I am unable to move it into the designated area. I can still move it up and down.

Screenshot taken from 6+ simulator:
![image](https://cloud.githubusercontent.com/assets/81757/5673175/9900df48-9766-11e4-853b-00ef6edef370.png)

For comparison: taken from the 5 simulator (OS 8.1): 
![image](https://cloud.githubusercontent.com/assets/81757/5673241/2b050036-9767-11e4-83d6-318d5b180173.png)

**Comment by hambly** [comment]
@miwillhite Please update to the latest version of the ShipLib Framework (2.0.5): https://github.com/sincerely/shiplib-ios-framework/releases/tag/2.0.5 or via Cocoapods: https://github.com/CocoaPods/Specs/tree/master/Specs/ShipLib

Version 2.0.x adds iPhone 6/6+ support and iOS 7/8 styles.

**Comment by miwillhite** [comment]
:+1:
